version: '3'

services:
  mqtt-arm:
    image: valentinvieriu/alpine-mosquitto-arm
    ports:
      - 1883:1883
    networks:
      - hw3
  mqtt:
    image: trafex/alpine-mosquitto
    ports:
      - 1883:1883
    networks:
      - hw3
  face-forwarder:
    image: austin/face-forwarder
    build:
      context: .
      dockerfile: docker/face-forwarder.Dockerfile
    depends_on:
      - mqtt-arm
    networks:
      - hw3
    command:
      - --dest-host
      - 198.11.248.77
  face-finder:
    image: austin/face-finder
    build: 
      context: .
      dockerfile: docker/face-finder.Dockerfile
    command:
      - --debug
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
    devices: 
      - /dev/video1:/dev/video0
    depends_on:
      - mqtt-arm
    networks:
      - hw3
  face-storer:
    image: austin/face-storer
    build:
      context: .
      dockerfile: docker/face-storer.Dockerfile
    networks:
      - hw3
    volumes:
      - ./secrets/:/app/.bluemix/
    depends_on:
      - mqtt

networks:
  hw3:
    driver: bridge
    